version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: pos_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tienda_abarrotes
      MYSQL_USER: user_tienda
      MYSQL_PASSWORD: password_tienda
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script automático de inicialización

  web:
    build: ./backend
    container_name: pos_flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=user_tienda
      - DB_PASSWORD=password_tienda
      - DB_NAME=tienda_abarrotes
    depends_on:
      - db

volumes:
  db_data:
